@startuml Manage a hospital (POST)

header Sample VacQ Sequence Diagram
footer 6631321321 Thanagorn Chaiyut
title "Manage a hospital (POST)"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:hospitals" as routerHospitals
participant "<<controllers>>\n:hospitals" as controllersHospitals
participant "<<model>>\n:Hospital" as modelHospital
database "<<MongoDB>>\n:hospitals" as HospitalsDatabase

client->server ++:req.post('/api/v1/hospitals')
server->routerHospitals ++:app.use('/api/v1/hospitals', hospitals)
routerHospitals -> controllersHospitals ++:createHospital()
controllersHospitals->modelHospital ++:create(req.body)
modelHospital ->HospitalsDatabase ++: HospitalSchema
HospitalsDatabase --> modelHospital --: hospital
controllersHospitals <-- modelHospital --:hospital
controllersHospitals->client --:response

@enduml
